const AppString = {
  selectValue: '',

  loginScreen: {
    association: 'In association with',
    title: 'Sign In',
    forgotPassword: 'Forgot Password?',
    login: 'Login',
    signupString: "Don't have an account? ",
    signup: 'Sign Up',
    presenting: 'Presenting',
    consumerNo: 'Consumer Number',
  },

  mPinScreen: {
    fingerprint:
      'Fingerprint has no enrolled fingers. Please go to settings and enable fingerprint on this device',
    login: 'Log In With',
    fingerprintText: 'Fingerprint',
    pin: '4-digit PIN',
    signin: 'SIGN IN WITH DIFFERENT ACCOUNT',
  },

  otpScreen: {
    title: 'Verify User',
    description:
      'Please enter the 6-digit code sent to your mobile for verification.',
    button: 'Verify OTP',
    error: 'Please enter valid otp',
    otpText: 'Resend OTP',
    otp: 'Get OTP',
  },

  chooseConsumerScreen: {
    title: 'Choose Consumer',
  },

  portfolioScreen: {
    header: 'Portfolio',
    button1: 'Go To Trading',
    button2: 'calender',
    buttonEnergy: 'Energy Calculator',
  },

  mpinSetScreen: {
    title: 'Set MPIN',
    description: 'Please enter the 4-digit pin code.',
    confirmdescription: 'Please confirm the 4-digit pin code.',
    confirm: 'Confirm',
    error: 'Please enter valid MPIN',
    errorSame: 'Please enter same MPIN',
  },

  mpinConfirmScreen: {
    title: 'Confirm MPIN',
    description: 'Please enter the 4-digit pin code.',
    confirm: 'Log In With MPIN',
    confirmBio: 'Log In With Fingerprint',
    error: 'Please enter valid MPIN',
    errorSame: 'Please enter same MPIN',
    forgotPin: 'Forgot PIN',
  },

  registrationScreen: {
    type: 'Choose your Consumer Type',
    terms: 'I accept terms of use and privacy policy.',
    viewBill: 'View Sample Bill',
  },

  loadDetailsScreen: {
    header: 'Load Details',
  },

  DirectTradingConfirmationScreen: {
    name: 'Dynamic Trading',
    orderType: 'Order Type',
    ConfirmationDialog: {
      title: 'Order Confirmation',
      date: 'Date',
      units: 'Units',
      units1: 'Units (kWh)',
      ltp: 'LTP (₹)',
      ltp1: 'LTP',
      rate: 'Rate',
      rate1: 'Rate (₹)',
      remaning: `Daily\nRemainig\nUnits (kWh)`,
      depth: `Market\nDepth`,
      instrument: `Instrument\nName	`,
      amount: `Amount`,
      timeslot: `Time Slot`,
    },
    dateWarning: 'Please check date for trading',
    timeSlotWarning: 'Please select time slot for trading',
    unitWarning: 'Unit or rate must be gretar than 0',
    unitWarnings: 'Unit must be gretar than 0',
    monthWarning: 'Order Units limit exceed',
    noDataDailog: {
      icon: 'noDataFound',
      title: 'Dynamic Trading',
      description: `No trade available for the day `,
    },
  },
  submit: 'Submit',
  ChangePasswordScreen: {
    name: 'Reset Password',
    screenName: 'resetPassword',
    oldPassword: {
      title: 'Old Password',
      placeholder: 'Old Password',
    },
    password: {
      title: 'Password',
      placeholder: 'Password',
    },
    confirm: {
      title: 'Confirm Password',
      placeholder: 'Confirm Password',
    },
    change: 'Change Password',
  },
  ResetPasswordScreen: {
    name: 'Change Password',
    screenName: 'Change Password',
    oldPassword: {
      title: 'Old Password',
      placeholder: 'Old Password',
    },
    password: {
      title: 'Password',
      placeholder: 'Password',
    },
    confirm: {
      title: 'Confirm Password',
      placeholder: 'Confirm Password',
    },
    change: 'Change Password',
  },
  LineChart: {
    noDataDailog: {
      icon: 'noDataFound',
      title: '',
      description: `No data available for the day `,
    },
  },
  gotoTradingScreen: {
    text: 'Choose your Market Type',
    intradayHeader: 'INTRADAY PPA',
    intradayTitle:
      'Intraday allowing participants to buy/sell electricity for current day.',
    dayAhead: 'DAY AHEAD PPA',
    dayAheadTitle:
      'Day-Ahead allowing participants to buy/sell electricity for next day. ',
    termAhead: 'TERM AHEAD PPA',
    termAheadTitle:
      'Term-Ahead allowing participants to buy/sell electricity for next 7 days.',
    interaDayClose: `Trading is not allowed after 5:00 PM. The market is closed and will reopen tomorrow.
For intraday trading, please place your orders at least four time blocks before the scheduled start.`,
    dayAheadClose: `Trading is not allowed after 5:00 PM. The market is closed and will reopen tomorrow. 
For day-ahead trading, Kindly place your orders before 5:00 PM.`,
  },
  TradingScreen: {
    name: 'Trade',
    orderType: 'Order Type',
  },
  launchScreen1: {
    lable: 'Trade Trust Network',
    header: 'Peer-to-Peer Transactions',
    content:
      'Enable users to trade directly with each other without intermediaries, allowing for faster and more efficient transactions.',
  },
  launchScreen2: {
    header: 'Customizable Orders',
    content:
      'Allow users to create customized orders, such as limit orders or market orders, to execute trades according to their specific preferences.',
  },
  launchScreen3: {
    header: 'User Ratings and Reviews',
    content:
      'Enable users to rate and review each other based on their trading experiences, helping to build trust within the community.',
  },
  dashboardScreen: {
    header : 'Dashboard',
    news: 'News & Update: ',
    headline: `Empowering Future Energy: NPCL's Blockchain-based Trading Revolution.`,
    trendsText: `Orders Trades & Settlement`,
    order: 'ORDER',
    trade: 'TRADE',
    settlement: 'SETTLEMENT',
    tradeText: `Trade Trends`,
    viewMore: 'View more',
    marqueeText:
      'Energy scheduling should be completed at least four-time blocks before the intended schedule. Trading hours are from 7:00 AM to 5:00 PM IST.',
  },
  name: 'Name',
  code: 'Platform Id',
  date: 'Date',
  change: 'Change (%)',
  units: 'Units',
  ltp: 'Ltp',
  rate: 'Rate',
  avgRate: 'Avg. Rate',
  buySell: `Buy / Sell`,
  trade: 'Trade',
  adminApproval: `Wait for admin approval`,
  homeScreen: {
    verification: {
      header: 'verification',
      subHeader:
        'Any sensitive information, businesses can keep all user and business information secure',
      icon: 'verification',
    },
  },
  OnBoardingScreen: {
    verification: {
      title: 'ENERGY TRADING PLATFORM',
      subHeader: 'Please wait, do not close or reload page while processing...',
    },
    verificationFailed: {
      icon: 'close-circle-outline',
      title: 'Error while checking user',
      description: `Consumer not found`,
    },
  },
  OnBoardingDetailScreen: {
    header: 'User Onboarding',
  },
  PasswordScreen: {
    verification: {
      icon: 'checkmark-circle',
      title: 'Your password has been updated.',
      description: 'You can now use your new password to log in.',
    },
  },
  directTrading: {
    icon: 'checkmark-circle',
    title: 'Request Submitted',
    description: `Your request has been submitted successfully.`,
  },
  loadScreen: {
    icon: 'checkmark-circle',
    title: 'Request Submitted',
    description: `Your request has been submitted successfully, Our team will review the document and notify you via email once the review process is complete.\n\nWe appreciate your patience and cooperation.`,
  },
  profile: {
    icon: '',
    title: 'Complete your profile form submission',
    description: `It appears that you haven't finished filling out your profile form. Please take a moment to complete all required fields. Your profile information helps us provide you with a personalized experience tailored to your needs`,
  },
  profileScreen: {
    title: 'Profile',
    verified: 'Verified',
    unverfied: 'Unverified',
    email: 'Email Id',
    fullName: 'Full Name',
    mobile: 'Mobile Number',
    consumerNo: 'Consumer No.',
    address: 'Address',
    changePassword: 'Change Password',
    load: 'Load Details',
    meter: 'Meter Details',
    plant: 'Plant Details',
    contratualLoad: `Sanctioned Load /\n Contractual Load`,
    meterNo: 'Meter No',
    contractedCapacity: 'Exiting Solar Capacity',
    bill: 'Invoice',
    support: 'Contact & Support',
    logout: 'Logout',
    faq: 'FAQs',
    profileDetails: 'Profile Details',
    notification: 'Notification',
    TariffCode: 'Rate Code',
    energyCalculation: 'Energy Saving Calculator',
  },
  verification: {
    icon: '',
    title: 'Wait for Approval from admin',
    description: `Please be patient while we review your profile submission. You can check the current status by clicking the 'Check Status' button`,
  },
  meterDetailScreen: {
    icon: 'checkmark-circle',
    title: 'Congratulation!',
    description: `Your Account has been created successfully.\n\nNow Login & Complete your profile setup.`,
    header: 'Meter Details',
  },
  plantDetailScreen: {
    header: 'Plant Details',
  },
  loginViaOtp:
    'Please enter your registered mobile number to reset your password!',
  loginViaOtpConsumer: 'Consumer Number ',

  marketScreen: {
    icon: 'noDataFound',
    title: 'No Data Found',
    description: `Your consumer trading list is not generated.`,
    name: 'marketScreen',
    marketCard: {
      orders: 'orders',
      available: 'Available Units',
      amount: 'Amount',
      rate: 'Rate',
    },
    loadMore: 'Load More',
  },
  tradeScreen: {
    header: 'Order Confirmation',
    remaining: 'Remaining',
    dailyUnits: 'Daily Units',
    monthlyUnits: 'Monthly Units',
    name: 'Name',
    units: 'Units',
    ratePerUnits: 'Rate',
    tradeAmount: 'Amount ',
    submit: 'Submit',
  },
  orderScreen: {
    icon: 'noDataFound',
    title: 'No Data Found',
    description: `You have not created any orders yet.`,
    description1: `There are no active pending orders Kindly check the 'Settled / All Orders' tab`,
  },
  blockchainScreen: {
    header: 'Blockchain Details',
    icon: 'noDataFound',
    title: 'No Details',
    description: `Blockchain details not found.`,
    viewInBlockchain: 'VIEW IN BLOCKCHAIN EXPLORER',
    supplierCOde: 'Prosumer',
    buyerCode: 'Consumer',
    platformId: 'Platform Id',
    tradeUnit: 'Trade Unit',
    transactionCharges: 'Transaction Charges',
    wheelingCharges: 'Wheeling Charges',
    ratePerUnit: 'Rate per Unit',
    tradeAmount: 'Trade Amount',
    settledUnit: 'Settled Unit',
    settledAmount: 'Settled Amount',
    time: 'Contract Date',
    sync: 'Is Sync With Blockchain',
    endorsed: 'Is Endorsed',
    failReason: 'Remarks',
    txId: 'Transaction Id',
    timeslot: 'Time Slot',
  },
  orderDetailsScreen: {
    tradeTransaction: 'Trade Transactions',
    tradeUnit: 'Trade Unit',
    ratePerUnit: 'Rate per Unit',
    tradeAmount: 'Trade Amount',
    unsettledUnit: 'Unsettled Unit',
    settledUnit: 'Settled Unit',
    settledAmount: 'Settled Amount',
    completed: 'Completed',
  },
  estimatedAmount: 'Estimated Amount',
  wheelingCharges: 'Wheeling Charges',
  transactionCharges: 'Transaction Charges Inc.GST.',
  currentBillScreen: {
    icon: 'noDataFound',
    title: 'No Data Found',
    description: `Your bill is not generated for this month.`,
    billType: 'Bill Type',
    scheduleEnergy: 'Scheduled energy on Platform',
    energyPurchasedBuy: 'Energy Purchased from Platform',
    mutuallyAgreed: 'Mutually Agreed transaction Price',
    discomTariff: 'Discom Rate Code',
    transactionCharges: 'Service Provider Charges',
    wheelingCharges: 'Wheeling charges',
    UnderdrawalUnitsBuy: 'Underdrawal Units',
    OverdrawalUnitBuy: 'Overdrawal Unit',
    EnergyCharges: 'Energy Charges on P2P',
    OverdrawalCharges: 'Overdrawal Charges',
    UnderdrawalCharges: 'Underdrawal Charges',
    TotalPayableBuy: 'Total Payable towards platform energy',
    netBenfit: 'Net Benefit',
    energySoldSell: 'Energy Sold to Platform',
    UnderInjectionUnitsSell: 'Under Injection Units',
    overInjectionUnitsSell: 'Over Injection Unit',
    ReceivableSell: 'Receivable from over injection',
    underInjectionSell: 'Under Injection Charges',
    totalRecievableSell: 'Total Receivable towards Platform',
    settledTransaction: 'Settled Transaction on Platform ',
    underInjectionUnits: 'Under Injection Units',
    energyPurchasedFromDiscom: 'Energy Purchased from Discom',
    energySoldToP2pPlatform: 'Energy sold to Platform',
    contractedDemand: 'Contracted Demand',
    loadOnP2pPlatform: 'Load on platform',
    transactionPrice: 'Service Provider Transaction charge / units',
    receivable: 'Receivable Amount',
    payble: 'Payble Amount',
    energyCharges: 'Energy Charges For energy supplied by Discom',
    demandCharges: 'Demand Charges For energy supplied by Discom',
    total: 'Total Bill Amount',
    download: 'DOWNLOAD',
    payBill: 'PAY BILL',
    viewBill: 'View Bill',
    currentBill: 'CURRENT BILL',
    billHistory: 'BILL HISTORY',
  },
  historyBillScreen: {
    icon: 'billNotFound',
    title: 'No Data Found',
    description: `Your bills not generated.`,
  },
  contactAndSupportScreen: {
    header: 'Contact Us',
    infoText:
      'Feel free contact us any time. We will get back to you as soon as we can!',
    contactNo: '+91 XXX XXX XXXX',
    emailId: 'support@p2p.com',
    address:
      'No B - 4 Nabhikiya Urja Bhavan, Darbari, Barc, North Gate, Anushakti Nagar, Npcil, Mumbai, Maharashtra 400094',
  },
  EnergyCalculationScreen: {
    header: 'Energy Calculator',
    submit: 'Calculate',
  },
  FaqScreen: {
    header: 'FAQs',
    q1: 'What is a NPCL Saur Mitra Energy Trading?',
    q2: 'How does the application work?',
    q3: 'How do I update the application?',
    q4: 'How can I contact customer support?',
    q5: 'Who is Consumer and Prosumer?',
    q6: 'What devices are supported?',
    q7: 'Do I need an internet connection to use the application?',
    q8: 'How do I verify my account?',
    a1: 'NPCL Saur Mitra energy trading is an innovative approach to energy distribution that allows individuals or entities to buy and sell energy',
  },

  google_url: 'https://www.google.com/',
  login_bottom_text: '© 2024 NPCL. All rights reserved',
  rupee: '₹',
  calenderScreen: {
    viewList: 'View List',
    viewCalender: 'View Calender',
    gotoTrading: 'Go To Trading',
  },
  kwh: 'kWh',
  kw: 'kW',
  kg: 'Kg',
  timeslot: 'Time Slot	',
};

export default AppString;
